site_name: Superpygeon Documentation
site_url: https://kecilin-team.github.io/spy-docs
site_author: Kecilin Team
site_description: Complete documentation for Superpygeon - AI-powered video analytics system

repo_name: Kecilin-Team/spy-docs
repo_url: https://github.com/Kecilin-Team/spy-docs
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.footer

plugins:
  - search
  - encryptcontent:
      password_button_text: 'Unlock'
      summary: 'This page is password protected'
      placeholder: 'Enter password'
      decryption_failure_message: 'Invalid password'
      encryption_info_message: 'This content is protected by password'
      password_inventory:
        installation.md: 'GITHUB_SECRET_PASSWORD'
        config-builder.md: 'GITHUB_SECRET_PASSWORD'
        feature.md: 'GITHUB_SECRET_PASSWORD'
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Exclude files from being processed
exclude_docs: |
  architecture.md
  contributing.md

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Config Builder: config-builder.md
  - Features: feature.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kecilin-Team/spy-docs
  version:
    provider: mike

copyright: Copyright &copy; 2025 AssistX Vision Team